language: r
sudo: false

branches:
  only:
    - master

cache:
  packages: yes
  directories:
    - $HOME/bin

r_packages:
  - bookdown
  - checkpoint
    
r_github_packages:
  - DeclareDesign/DeclareDesign

script:
  - Rscript -e 'library(checkpoint); found_packages <- scanForPackages(".", use.knitr = TRUE)$pkgs; install.packages(found_packages[!found_packages%in% installed.packages()])'
  - Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::gitbook")'
