language: r
sudo: false

branches:
  only:
    - master

cache:
  packages: yes
  directories:
    - $HOME/bin
    
r_github_packages:
  - DeclareDesign/DeclareDesign
  - rstudio/blogdown

script:
  - ls
  - Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::gitbook")'
