---
knit: "bookdown::render_book"
title: "Declaring and Diagnosing Research Designs"
author: "Graeme Blair, Jasper Cooper, Alexander Coppock, Macartan Humphreys"
bibliography: [bib.bib, packages.bib, designs.bib]
output: pdf_document
bookdown::pdf_book:
  citation_package: natbib
  includes:
    in_header: preamble.tex
    template: template.tex
  keep_tex: yes
  latex_engine: xelatex
description: "Design design design."
documentclass: book
fontfamily: mathpazo
fontsize: 11pt
github-repo: rstudio/rdb
link-citations: yes
bookdown::gitbook:
  config:
    toc:
      after: |
        <li><a href="http://DeclareDesign.org" target="blank">DeclareDesign</a></li>
      before: |
        <li><a href="./">Declaring and Diagnosing Research Designs</a></li>
      collapse: section
  css: style.css
  split_by: section
site: bookdown::bookdown_site
biblio-style: apalike
---


```{r include=FALSE}
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```


```{r, echo=FALSE, warning=FALSE}
library(DeclareDesign)
library(ggplot2)
library(dplyr)
library(tidyr)
library(gridExtra)
library(forcats)
library(knitr)

set.seed(42)

rerun_templates <- FALSE

intro_path   <- "01_Part_A_MIDA"
designs_path <- "02_Part_B_Designs"
outro_path   <- "03_Part_C_Principles"
principles_path <- "03_Part_C_Principles"

dd_theme <-
  theme_bw()  %+replace%
  theme(
    axis.ticks = element_blank(),
    axis.line = element_blank(),
    panel.border = element_blank(),
    panel.grid.major = element_line(color = '#eeeeee'),
    strip.background = element_blank(),
    legend.position = "bottom"
    )

```

# Welcome {-}

In *Declaring and Diagnosing Research Designs*, we aim to present a comprehensive view of modern research design. 



