```{r,echo=FALSE,eval=FALSE}
tempR <- tempfile(fileext = ".R")
library(knitr)
purl("../index.Rmd", output=tempR)
source(tempR)
unlink(tempR)
```



### MIDA


- **M**odel:

- **I**nquiry:

- **D**ata strategy:

- **A**nswer strategy:


### Declaration


```{r}
rdd_template <- function(N){
  require(rdrobust)
  control <- function(running) {
    as.vector(poly(running, 4, raw = T) %*% c(1, -1, -.5, 1))
  }
  treatment <- function(running) {
    as.vector(poly(running, 4, raw = T) %*% c(0, -1, .5, .8)) + .15
  }
  population <- declare_population(
    N = N,
    running = runif(N,-1,1),
    noise = rnorm(N,0,.2),
    Z = 1 * (running > 0)
  )
  potential_outcomes <- declare_potential_outcomes(
    formula = Y ~ Z * treatment(running) + (1 - Z) * control(running) + noise,
    assignment_variable_name = "Z",
    condition_names = c(0, 1)
  )
  estimand <- declare_estimand(LATE = treatment(0) - control(0))
  estimator <- declare_estimator(estimator_function = function(data){
    rd_out <- with(data,rdrobust(y = Y, x = running, bwselect = "mserd"))
      return(data.frame(
        est = rd_out$coef["Conventional","Coeff"],
        p = rd_out$pv["Conventional","P>|z|"],
        se = rd_out$se["Conventional","Std. Err."],
        ci_upper = rd_out$ci["Conventional","CI Upper"],
        ci_lower = rd_out$ci["Conventional","CI Lower"]))
  },
  estimand = estimand,
  label = "rdrobust")
  rdd_design <- declare_design(
    population,
    potential_outcomes,
    estimand,
    reveal_outcomes,
    estimator
  )
  return(rdd_design)
}

```

```{r, echo=FALSE, eval = rerun_templates}
Ns <- seq(150, 1000, 50)
designs <- quick_design(template = rdd_template, N = Ns,expand = TRUE)

diagnosis <- diagnose_design(designs,sims = 500,bootstrap = FALSE)
diagnosis$simulations

saveRDS(diagnosis, file = "../examples_data/08_rdd.RDS")
```

```{r, echo=FALSE, eval = !rerun_templates}
diagnosis <- readRDS(file = "../examples_data/08_rdd.RDS")
```

```{r, eval = FALSE}

Ns <- seq(50, 1000, 50)

designs <- quick_design(template = rdd_template, N = Ns,expand = TRUE)

diagnosis <- diagnose_design(designs,sims = 500,bootstrap = FALSE)

```


### Takeaways

```{r,echo=FALSE}
control <- function(running) {
  as.vector(poly(running, 4, raw = T) %*% c(1, -1, -.5, 1))
}
treatment <- function(running) {
  as.vector(poly(running, 4, raw = T) %*% c(0, -1, .5, .8)) + .15
}
rdd_design <- rdd_template(1000)
mock_data <- draw_data(rdd_design)
treatment_frame <- data.frame(
  running = seq(-1,1,.005),
  Y = treatment(seq(-1,1,.005)),
  observed = ifelse(seq(-1,1,.005) > 0,"a","b"),
  Z = 1
  )
control_frame <- data.frame(
  running = seq(-1,1,.005),
  Y = control(seq(-1,1,.005)),
  observed = ifelse(seq(-1,1,.005) <= 0,"a","b"),
  Z = 0
  )
plot_frame <- rbind(treatment_frame,control_frame)

ggplot(plot_frame,aes(x = running, y = Y, color = as.factor(Z))) + 
  geom_line(aes(linetype = observed)) +
  geom_point(data = mock_data, alpha = .2, size = .5) +
  scale_linetype_discrete(name = "", labels = c("Observable","Unobservable")) +
  scale_color_discrete(name = "", labels = c("Untreated","Treated")) +
  geom_vline(xintercept = 0, size = .05) +
  xlab("Running Variable") + 
  geom_segment(aes(x = 0,xend = 0, y = control(0),yend = treatment(0)),color = "black") +
  dd_theme
```






### Exercises 





















